#!/bin/bash

# Usage: ./run-master.sh <#workers>
if [ $# -ne 1 ]; then
  echo "Usage: $0 <number_of_workers>"
  exit 1
fi

NUM_WORKERS=$1

SCRIPT_DIR="$(dirname "$(readlink -f "$0")")"

cd "${SCRIPT_DIR}/distributed-sorting"

sbt -J-Xmx16G -J-Xms10G \
    -Dsbt.log.noformat=true \
    --error --supershell=false \
    "runMain MasterMain ${NUM_WORKERS}"
