#!/bin/bash

# Usage: ./run-master.sh <#workers>
if [ $# -lt 1 ] || [ $# -gt 2 ]; then
  echo "Usage: $0 <number_of_workers> [-v]"
  exit 1
fi

NUM_WORKERS=$1
VERBOSE="FALSE"
if [ "$2" == "-v" ]; then
  VERBOSE="TRUE"
fi
SCRIPT_DIR="$(dirname "$(readlink -f "$0")")"

cd "${SCRIPT_DIR}/distributed-sorting"

if [ "$VERBOSE" == "TRUE" ]; then
  sbt -J-Xmx16G \
    -Dsbt.log.noformat=true \
    --error --supershell=false \
    "runMain MasterMain ${NUM_WORKERS} -v"
else
  sbt -J-Xmx16G \
      -Dsbt.log.noformat=true \
      --error --supershell=false \
      "runMain MasterMain ${NUM_WORKERS}"
fi